### ISSUE TITLE
Closing itself with below error after choosing changing save dir.

### ISSUE THREAD

**Issue by Md-Hasnat-Hosen-Arafat** [heartexlabs/labelImg#936]
Traceback (most recent call last):
  File "labelImg.py", line 1360, in open_dir_dialog
    self.import_dir_images(target_dir_path)
  File "labelImg.py", line 1375, in import_dir_images
    self.open_next_image()
  File "labelImg.py", line 1430, in open_next_image
    self.change_save_dir_dialog()
  File "labelImg.py", line 1310, in change_save_dir_dialog
    self.show_bounding_box_from_annotation_file(self.file_path)
  File "labelImg.py", line 1199, in show_bounding_box_from_annotation_file
    xml_path = os.path.splitext(file_path)[0] + XML_EXT
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 202, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

- **OS:**
- **PyQt version:**

**Comment by kimhegg** [comment]
same error when attempting the same thing.. (windows 11)
